station/urls.py
from django.urls import path, include #include enables us to get the template from another app
from . import views #this enables us to interact with views.py

app_name = 'station_app'

urlpatterns = [
    path('', views.report, name="station"),
]

weather_station/urls.py
from django.contrib import admin
from django.urls import path, include #include enables us to get the template from another app
from . import views #this enables us to interact with views.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #this is for static assets folder where we put css
from django.conf.urls.static import static #this is for media purposes
from django.conf import settings #this is also for media purposes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('weather/', include('station.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

station/models.py
from django.db import models

# Create your models here.
class Reading(models.Model):
    location = models.CharField(max_length=100)
    weather = models.CharField(max_length=20)
    wind_str = models.CharField(max_length=100)
    temp = models.IntegerField()
    humidity = models.CharField(max_length=100)
    precip = models.CharField(max_length=50)
    icon_url = models.URLField()
    observation_time = models.CharField(max_length=100)

station/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from .models import Reading
from .worker import fetch_data

# Create your views here.
def report(request):
    fetch_data()
    data = Reading.objects.last()
    return render(request, 'station/station.html', { 'data': data })

weather_station/views.py
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('Homepage')
    return render(request, 'homepage.html')

station/templates/station/station.html
{% extends 'homepage.html' %}
{% block content %}
    <div class="panel panel-default text-center">
        <br/><br/>
        <b>{{ data.observation_time }}</b><br/><br/>
        Location - <b>{{ data.location }}</b><br/><br/>
        Weather - <b>{{ data.weather }}</b> <img src="{{ data.icon_url }}"></img><br/><br/>
        Wind - <b>{{ data.wind_str }}</b><br/><br/>
        Temperature - <b>{{ data.temp }}</b><br/><br/>
        Humidity - <b>{{ data.humidity }}</b><br/><br/>
        Precip - <b>{{ data.precip }}</b><br/><br/>
        
    </div>
{% endblock %}

templates/homepage.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Weather Station</title>
        <link rel="icon" href="/static/icon.png">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class="container-fluid">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>                        
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Weather Station</a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'station_app:station' %}">Weather Page</a></li>
                </ul>
              </div>
            </div>
        </nav>
        <div class="panel panel-default"></div>
        
        {% block content %}
            <h2>About</h2>
            <img src="/static/icon.png"></img>
            <p>
                A personal weather station is a set of weather measuring instruments that you can install at your own home or business. The number of instruments can vary, but most personal weather stations include instruments to measure temperature, relative humidity, pressure, rain fall, and wind speed and direction. Scroll down to learn more about these sensors and how a personal weather station works.
            </p>
            <p>
            <p>
                Go to <a href="https://www.wunderground.com/weather/api/"><b>Visit</b></a> for more info
            </p>
            <p>
                Go to <a href="{% url 'station_app:station' %}"><b>Weather Page</b></a> for more info
            </p>
        {% endblock %}
        <div class="panel panel-default text-center"></div>
    </body>
</html>